server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 1200
  jetty:
    max-http-post-size: 52428800

spring:
  application:
    name: lvee_note
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lvee_note?useSSL=false&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      pool-name: DatebookHikariCP
      #最小连接数
      minimum-idle: 8
      #最大连接数
      maximum-pool-size: 200
      #更新是否自动提交
      auto-commit: true
      #连接超时的最大时长（毫秒）
      idle-timeout: 600000
      #连接的生命时长（毫秒）
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

rockertmq:
  namesrvAddr: 127.0.0.1:9876

lvee:
  redis: true