server:
  port: 8080
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
  servlet:
    context-path: /

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

# 数据源
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 日志
logging:
  level:
    root: info
    com.keduw.vortex.dao: debug

# 健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 开关
vortex:
  open:
    redis: true
    security: true
